import Link from "next/link";
import { listVouchers } from "@/lib/queries/billing";
import { db } from "@/lib/db";
import * as s from "@/lib/schema";
import { Pill } from "@/components/Pill";
import { dateTimeStr } from "@/lib/format";
import { generateVouchers, redeemVoucher } from "@/lib/actions/billing";

export const dynamic = "force-dynamic";

export default async function VouchersPage({ searchParams }: { searchParams: Promise<{ status?: string }> }) {
  const sp = await searchParams;
  const [vouchers, tariffs] = await Promise.all([listVouchers({ status: sp.status }), db.select().from(s.tariffs)]);
  const unused = vouchers.filter((v) => v.status === "unused").length;

  return (
    <>
      <div className="page-head">
        <div>
          <div className="crumb"><Link href="/billing">Billing</Link> / Vouchers</div>
          <h1>Vouchers</h1>
          <p>{unused} unused of {vouchers.length} shown. Codes generated here are real rows — money-like credentials, kept out of CSV export by design.</p>
        </div>
      </div>

      <div className="split">
        <div className="card">
          <header><h3>Generate batch</h3></header>
          <form action={generateVouchers} className="stack">
            <div className="field">
              <label>Plan</label>
              <select name="tariffId" required defaultValue="">
                <option value="" disabled>Select plan…</option>
                {tariffs.map((t) => <option key={t.id} value={t.id}>{t.name} — {t.priceMmk.toLocaleString()} MMK</option>)}
              </select>
            </div>
            <div className="field">
              <label>Count</label>
              <input name="count" type="number" min={1} max={100} defaultValue={10} />
            </div>
            <button className="btn primary" type="submit">Generate</button>
          </form>
        </div>

        <div className="card">
          <header><h3>Redeem</h3></header>
          <form action={redeemVoucher} className="stack">
            <div className="field">
              <label>Voucher code</label>
              <input name="code" placeholder="TF-XXXXXX-000" required />
            </div>
            <div className="field">
              <label>Customer ID</label>
              <input name="customerId" placeholder="CUS-0001" required />
            </div>
            <button className="btn primary" type="submit">Redeem</button>
          </form>
        </div>
      </div>

      <div className="card" style={{ marginTop: 14 }}>
        <header>
          <h3 style={{ flex: 1 }}>Voucher stock</h3>
          <div className="row">
            <Link href="/billing/vouchers" className={!sp.status ? "btn sm primary" : "btn sm ghost"}>All</Link>
            <Link href="/billing/vouchers?status=unused" className={sp.status === "unused" ? "btn sm primary" : "btn sm ghost"}>Unused</Link>
            <Link href="/billing/vouchers?status=used" className={sp.status === "used" ? "btn sm primary" : "btn sm ghost"}>Used</Link>
          </div>
        </header>
        <div className="table-wrap">
          <table>
            <thead><tr><th>Code</th><th>Plan</th><th>Status</th><th>Generated by</th><th>Redeemed by</th><th>Redeemed at</th></tr></thead>
            <tbody>
              {vouchers.map((v) => (
                <tr key={v.id}>
                  <td className="num">{v.code}</td>
                  <td>{v.tariff?.name ?? "—"}</td>
                  <td><Pill status={v.status} /></td>
                  <td>{v.generatedBy}</td>
                  <td>{v.redeemedByName ?? "—"}</td>
                  <td>{dateTimeStr(v.redeemedAt)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </>
  );
}
